// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFeed(ctx context.Context, arg AddFeedParams) (Feed, error)
	AddFeedFollow(ctx context.Context, arg AddFeedFollowParams) (AddFeedFollowRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetFeeds(ctx context.Context) ([]Feed, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	ResetFeeds(ctx context.Context) error
	ResetUsers(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
