// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/database (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=./internal/database/mock/querier.go -package=mockdb ./internal/database Querier
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	database "gator/internal/database"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddFeed mocks base method.
func (m *MockQuerier) AddFeed(ctx context.Context, arg database.AddFeedParams) (database.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFeed", ctx, arg)
	ret0, _ := ret[0].(database.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFeed indicates an expected call of AddFeed.
func (mr *MockQuerierMockRecorder) AddFeed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFeed", reflect.TypeOf((*MockQuerier)(nil).AddFeed), ctx, arg)
}

// AddFeedFollow mocks base method.
func (m *MockQuerier) AddFeedFollow(ctx context.Context, arg database.AddFeedFollowParams) (database.AddFeedFollowRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFeedFollow", ctx, arg)
	ret0, _ := ret[0].(database.AddFeedFollowRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFeedFollow indicates an expected call of AddFeedFollow.
func (mr *MockQuerierMockRecorder) AddFeedFollow(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFeedFollow", reflect.TypeOf((*MockQuerier)(nil).AddFeedFollow), ctx, arg)
}

// CreatePost mocks base method.
func (m *MockQuerier) CreatePost(ctx context.Context, arg database.CreatePostParams) (database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, arg)
	ret0, _ := ret[0].(database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockQuerierMockRecorder) CreatePost(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockQuerier)(nil).CreatePost), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg database.CreateUserParams) (database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// GetFeedByUrl mocks base method.
func (m *MockQuerier) GetFeedByUrl(ctx context.Context, url string) (database.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedByUrl", ctx, url)
	ret0, _ := ret[0].(database.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedByUrl indicates an expected call of GetFeedByUrl.
func (mr *MockQuerierMockRecorder) GetFeedByUrl(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedByUrl", reflect.TypeOf((*MockQuerier)(nil).GetFeedByUrl), ctx, url)
}

// GetFeedFollowsForUser mocks base method.
func (m *MockQuerier) GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]database.GetFeedFollowsForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedFollowsForUser", ctx, userID)
	ret0, _ := ret[0].([]database.GetFeedFollowsForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedFollowsForUser indicates an expected call of GetFeedFollowsForUser.
func (mr *MockQuerierMockRecorder) GetFeedFollowsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedFollowsForUser", reflect.TypeOf((*MockQuerier)(nil).GetFeedFollowsForUser), ctx, userID)
}

// GetFeeds mocks base method.
func (m *MockQuerier) GetFeeds(ctx context.Context) ([]database.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeeds", ctx)
	ret0, _ := ret[0].([]database.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeeds indicates an expected call of GetFeeds.
func (mr *MockQuerierMockRecorder) GetFeeds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeeds", reflect.TypeOf((*MockQuerier)(nil).GetFeeds), ctx)
}

// GetNextFeedToFetch mocks base method.
func (m *MockQuerier) GetNextFeedToFetch(ctx context.Context) (database.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextFeedToFetch", ctx)
	ret0, _ := ret[0].(database.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextFeedToFetch indicates an expected call of GetNextFeedToFetch.
func (mr *MockQuerierMockRecorder) GetNextFeedToFetch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextFeedToFetch", reflect.TypeOf((*MockQuerier)(nil).GetNextFeedToFetch), ctx)
}

// GetPostForUser mocks base method.
func (m *MockQuerier) GetPostForUser(ctx context.Context, arg database.GetPostForUserParams) ([]database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostForUser", ctx, arg)
	ret0, _ := ret[0].([]database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostForUser indicates an expected call of GetPostForUser.
func (mr *MockQuerierMockRecorder) GetPostForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostForUser", reflect.TypeOf((*MockQuerier)(nil).GetPostForUser), ctx, arg)
}

// GetUserById mocks base method.
func (m *MockQuerier) GetUserById(ctx context.Context, id uuid.UUID) (database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockQuerierMockRecorder) GetUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockQuerier)(nil).GetUserById), ctx, id)
}

// GetUserByName mocks base method.
func (m *MockQuerier) GetUserByName(ctx context.Context, name string) (database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByName", ctx, name)
	ret0, _ := ret[0].(database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByName indicates an expected call of GetUserByName.
func (mr *MockQuerierMockRecorder) GetUserByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByName", reflect.TypeOf((*MockQuerier)(nil).GetUserByName), ctx, name)
}

// GetUsers mocks base method.
func (m *MockQuerier) GetUsers(ctx context.Context) ([]database.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]database.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockQuerierMockRecorder) GetUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockQuerier)(nil).GetUsers), ctx)
}

// MarkFeedFetched mocks base method.
func (m *MockQuerier) MarkFeedFetched(ctx context.Context, arg database.MarkFeedFetchedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFeedFetched", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFeedFetched indicates an expected call of MarkFeedFetched.
func (mr *MockQuerierMockRecorder) MarkFeedFetched(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFeedFetched", reflect.TypeOf((*MockQuerier)(nil).MarkFeedFetched), ctx, arg)
}

// RemoveFeedFollow mocks base method.
func (m *MockQuerier) RemoveFeedFollow(ctx context.Context, arg database.RemoveFeedFollowParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFeedFollow", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFeedFollow indicates an expected call of RemoveFeedFollow.
func (mr *MockQuerierMockRecorder) RemoveFeedFollow(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFeedFollow", reflect.TypeOf((*MockQuerier)(nil).RemoveFeedFollow), ctx, arg)
}

// ResetFeeds mocks base method.
func (m *MockQuerier) ResetFeeds(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFeeds", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFeeds indicates an expected call of ResetFeeds.
func (mr *MockQuerierMockRecorder) ResetFeeds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFeeds", reflect.TypeOf((*MockQuerier)(nil).ResetFeeds), ctx)
}

// ResetUsers mocks base method.
func (m *MockQuerier) ResetUsers(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetUsers", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetUsers indicates an expected call of ResetUsers.
func (mr *MockQuerierMockRecorder) ResetUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetUsers", reflect.TypeOf((*MockQuerier)(nil).ResetUsers), ctx)
}
